version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: dockerfile
    container_name: todo-api
    restart: always
    working_dir: /var/www
    volumes:
      - .:/var/www
    networks:
      - app-network
    depends_on:
      - db

  db:
    image: mysql:8
    container_name: todo_db
    restart: always
    environment:
      MYSQL_DATABASE: todo_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "3308:3306"
    networks:
      - app-network
    volumes:
      - db-data:/var/lib/mysql

  nginx:
    image: nginx:latest
    container_name: todo-nginx
    restart: always
    ports:
      - "8080:80"
    volumes:
      - .:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app-network
    depends_on:
      - app

networks:
  app-network:

volumes:
  db-data:
